export default [
  {
    id: "1",
    title: "Ceviche Mixto",
    price: 8.5,
    offerPrice: 8.00,
    stock: 12,
    img: "ceviche.jpg",
    category: "ceviche",
  },
  {
    id: "2",
    title: "Arroz con Mariscos",
    price: 15.99,
    offerPrice: 9.99,
    stock: 12,
    img: "arroz.jpg",
    category: "crocante",
  },
  {
    id: "3",
    title: "Trio Marino",
    price: 15.99,
    offerPrice: null,
    stock: 12,
    img: "trio.jpg",
    category: "crocante",
  },
  {
    id: "4",
    title: "Trio para 2",
    price: 25.99,
    offerPrice: null,
    stock: 12,
    img: "trio2.jpg",
    category: "crocante",
  },
  {
    id: "5",
    title: "Sudado Cabrilla",
    price: 15.99,
    offerPrice: null,
    stock: 12,
    img: "sudado.jpg",
    category: "caliente",
  },
  {
    id: "6",
    title: "Chupe de Camarones",
    price: 25.99,
    offerPrice: null,
    stock: 12,
    img: "chupe.jpg",
    category: "caliente",
  },
  {
    id: "7",
    title: "Ceviche de Pato",
    price: 20.00,
    offerPrice: null,
    stock: 12,
    img: "cevichepato.jpg",
    category: "criollo",
  },
  {
    id: "8",
    title: "carrot feugiat dui non mollis",
    price: 3.88,
    offerPrice: null,
    stock: 12,
    img: "carrot.jpg",
    category: "crocante",
  },
  {
    id: "9",
    title: "celery feugiat dui non mollis",
    price: 5.88,
    offerPrice: null,
    stock: 12,
    img: "celery.jpg",
    category: "crocante",
  },
  {
    id: "11",
    title: "cherry feugiat dui non mollis",
    price: 7.88,
    offerPrice: 6.88,
    stock: 12,
    img: "cherry.jpg",
    category: "ceviche",
  },
  {
    id: "22",
    title: "chicken feugiat dui non mollis",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "chicken.jpg",
    category: "criollo",
  },
  {
    id: "33",
    title: "Aliquam feugiat non chicken",
    price: 8.88,
    offerPrice: null,
    stock: 12,
    img: "chicken2.jpg",
    category: "criollo",
  },
  {
    id: "44",
    title: "clemen feugiat dui",
    price: 4.99,
    offerPrice: null,
    stock: 12,
    img: "clemen.jpg",
    category: "ceviche",
  },
  {
    id: "55",
    title: "cod feugiat dui non",
    price: 9.88,
    offerPrice: null,
    stock: 12,
    img: "cod.jpg",
    category: "criollo",
  },
  {
    id: "66",
    title: "corn feugiat non mollis",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "corn.jpg",
    category: "crocante",
  },
  {
    id: "77",
    title: "cucumber feugiat dui non",
    price: 4.88,
    offerPrice: 2.5,
    stock: 12,
    img: "cucumber.jpg",
    category: "crocante",
  },
  {
    id: "88",
    title: "dates feugiat non duilis",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "dates.jpg",
    category: "ceviche",
  },
  {
    id: "99",
    title: "fresh fish feugiat dui",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "fish.jpg",
    category: "criollo",
  },
  {
    id: "00",
    title: "fish lorem ipsum",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "fish2.jpg",
    category: "criollo",
  },
  {
    id: "111",
    title: "fish non mollis feugiat dui",
    price: 4.88,
    offerPrice: 3.25,
    stock: 12,
    img: "fish3.jpg",
    category: "criollo",
  },
  {
    id: "222",
    title: "lemon non mollis",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "lemon.jpg",
    category: "ceviche",
  },
  {
    id: "333",
    title: "Aliquam lime dui non mollis",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "lime.jpg",
    category: "ceviche",
  },
  {
    id: "444",
    title: "Aliquam mango dui non",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "mango.jpg",
    category: "ceviche",
  },
  {
    id: "555",
    title: "Aliquam meat dui non mollis",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "meat.jpg",
    category: "criollo",
  },
  {
    id: "666",
    title: "meat feugiat dui non mollis",
    price: 4.88,
    offerPrice: 4.0,
    stock: 12,
    img: "meat2.jpg",
    category: "criollo",
  },
  {
    id: "777",
    title: "Aliquam feugiat dui non meat",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "meat3.jpg",
    category: "criollo",
  },
  {
    id: "888",
    title: "mix vegetables feugiat dui non mollis",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "mix.jpg",
    category: "crocante",
  },
  {
    id: "999",
    title: "pears feugiat dui non mollis",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "pears.jpg",
    category: "ceviche",
  },
  {
    id: "000",
    title: "Aliquam pepper dui non mollis",
    price: 4.88,
    offerPrice: 3.99,
    stock: 12,
    img: "pepper.jpg",
    category: "crocante",
  },
  {
    id: "1111",
    title: "Aliquam salmon dui non mollis",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "salmon.jpg",
    category: "criollo",
  },

  {
    id: "bread1",
    title: "Sprouts Classic Seedsational Bread 14 oz",
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "bread.jpg",
    category: "postre",
  },
  {
    id: "bread2",
    title: "Traditional Corn Special Bread",
    price: 1.75,
    offerPrice: null,
    stock: 12,
    img: "bread2.jpg",
    category: "postre",
  },
  {
    id: "bread3",
    title: "Sprouts Classic Seedsational Bread",
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "bread3.jpg",
    category: "postre",
  },
  {
    id: "toast",
    title: "Oven Baked Garlic & Cheese Toast",
    price: 1.7,
    offerPrice: null,
    stock: 12,
    img: "toast.jpg",
    category: "postre",
  },
  {
    id: "toast2",
    title: "Oven Baked Italian Herb with Olive Oil Toast",
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "toast2.jpg",
    category: "postre",
  },
  {
    id: "cookies",
    title: "Raspberry Crumble Cookies",
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "cookies.jpg",
    category: "postre",
  },
  {
    id: "cookies2",
    title: "Chocolate Chip Cookies",
    price: 3.0,
    offerPrice: null,
    stock: 12,
    img: "cookies2.jpg",
    category: "postre",
  },
  {
    id: "cookies3",
    title: "Freshly Baked Chocolate Chip Cookie",
    price: 2.5,
    offerPrice: null,
    stock: 12,
    img: "cookies3.jpg",
    category: "postre",
  },
  {
    id: "muffin",
    title: "Thomas Cinnamon Raisin English Muffins",
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "muffin.jpg",
    category: "postre",
  },

  {
    id: "muffin2",
    title: "Mini Zucchini & Carrot Muffin",
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "muffin2.jpg",
    category: "postre",
  },

  {
    id: "muffin3",
    title: "Double Chocolate Oat Muffin ",
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "muffin3.jpg",
    category: "postre",
  },

  {
    id: "Gaseosa Helada/ sin Helar",
    title: "Coca Cola 1Lt",
    price: 9.00,
    offerPrice: null,
    stock: 12,
    img: "cocacola1lt.jpg",
    category: "bebida",
  },

  {
    id: "Gaseosa Helada / Sin Helar",
    title: "Inca Kola 1 Lt",
    price: 8.50,
    offerPrice: null,
    stock: 12,
    img: "incakola1lt.jpg",
    category: "bebida",
  },

  {
    id: "coffe2",
    title: "Caffee Nero Mocha Late",
    price: 1.8,
    offerPrice: null,
    stock: 12,
    img: "coffe2.jpg",
    category: "bebida",
  },

  {
    id: "coffe3",
    title: "Nescafe Clasico Instant Coffee",
    price: 2.2,
    offerPrice: null,
    stock: 12,
    img: "coffe3.jpg",
    category: "bebida",
  },

  {
    id: "coffe4",
    title: "Peet Coffee Decaf Major Dickason Blend",
    price: 2.4,
    offerPrice: 2.1,
    stock: 12,
    img: "coffe4.jpg",
    category: "bebida",
  },
];
