export default [
  {
    id: "1",
    title: "DanyBur",
    price: 5.50,
    offerPrice: null,
    stock: 12,
    img: "danybur.jpg",
    category: "hamburguesas",
  },
  {
    id: "2",
    title: "Juaneco",
    price: 7.50,
    offerPrice: null,
    stock: 12,
    img: "juaneco.jpeg",
    category: "hamburguesas",
  },
  {
    id: "3",
    title: "WillPoli",
    price: 9.00,
    offerPrice: null,
    stock: 12,
    img: "willpoli.jpeg",
    category: "hamburguesas",
  },
  {
    id: "4",
    title: "Carloncho",
    price: 12.00,
    offerPrice: null,
    stock: 12,
    img: "carloncho.jpeg",
    category: "hamburguesas",
  },
  {
    id: "5",
    title: "Huevo",
    price: 1.00,
    offerPrice: null,
    stock: 12,
    img: "huevo.jpg",
    category: "extra",
  },
  {
    id: "6",
    title: "Queso Cheddar",
    price: 1.50,
    offerPrice: null,
    stock: 12,
    img: "queso-chedar.jpg",
    category: "extra",
  },
  {
    id: "7",
    title: "Chorizo",
    price: 2.50,
    offerPrice: null,
    stock: 12,
    img: "chorizo.jpg",
    category: "extra",
  },
  {
    id: "8",
    title: "Papas Fritas",
    price: 2.00,
    offerPrice: null,
    stock: 12,
    img: "papas.jpg",
    category: "extra",
  },
  {
    id: "9",
    title: "DanyBur x 2 Unds",
    price: 11.00,
    offerPrice: 8.00,
    stock: 12,
    img: "danyburx2.jpg",
    category: "ofertas",
  },
  {
    id: "11",
    title: "Juaneco x 2 Unds",
    price: 15.00,
    offerPrice: 11.00,
    stock: 12,
    img: "juanecox2.jpg",
    category: "ofertas",
  },
  {
    id: "22",
    title: "WillPoli x 2 Unds",
    price: 18.00,
    offerPrice: 13.50,
    stock: 12,
    img: "willpolix2.jpg",
    category: "ofertas",
  },
  {
    id: "33",
    title: "Carloncho x 2 Unds",
    price: 24.00,
    offerPrice: 18.00,
    stock: 12,
    img: "carlonchox2.jpg",
    category: "ofertas",
  },
  {
    id: "Gaseosa Helada/ sin Helar",
    title: "Coca Cola 1.5Lt",
    price: 7.00,
    offerPrice: null,
    stock: 12,
    img: "cocacola1lt.jpg",
    category: "bebida",
  },

  {
    id: "Gaseosa Helada / Sin Helar",
    title: "Inca Kola 1.5Lt",
    price: 7.00,
    offerPrice: null,
    stock: 12,
    img: "incakola1lt.jpg",
    category: "bebida",
  },

  {
    id: "coffe2",
    title: "Café Nero Mocha Late",
    price: 3.00,
    offerPrice: null,
    stock: 12,
    img: "coffe2.jpg",
    category: "bebida",
  },
  {
    id: "coffe3",
    title: "Nescafe Clasico Instant Coffee",
    price: 2.00,
    offerPrice: null,
    stock: 12,
    img: "coffe3.jpg",
    category: "bebida",
  },

  {
    id: "coffe4",
    title: "Peet Coffee Decaf Major Dickason Blend",
    price: 2.4,
    offerPrice: 2.1,
    stock: 12,
    img: "coffe4.jpg",
    category: "bebida",
  },
  ];
